-- Database Scripts to Store Meme Data
CREATE DATABASE MEME;

USE MEME;

SET SQL_MODE='ALLOW_INVALID_DATES';

DROP TABLE MEME;

CREATE TABLE MEME(
    MEME_ID VARCHAR(255),
    INSERT_TIMESTAMP TIMESTAMP,
    UPDATE_TIMESTAMP TIMESTAMP,
    ID VARCHAR(255),
    URL VARCHAR(255),
    TITLE VARCHAR(1024),
    MEME_TYPE VARCHAR(255),
    NSFW VARCHAR(255),
    UP_VOTE_COUNT INT,
    DOWN_VOTE_COUNT INT,
    CREATION_TS TIMESTAMP,
    AUTHOR VARCHAR(255),
    AUTHOR_USER_ID VARCHAR(255),
    PROMOTED VARCHAR(255),
    IS_VOTE_MASKED VARCHAR(255),
    HAS_LONG_POST_COVER VARCHAR(255),
    IMAGE_WIDTH INT,
    IMAGE_HEIGHT INT,
    IMAGE_URL VARCHAR(255),
    SOURCE_DOMAIN VARCHAR(255),
    SOURCE_URL VARCHAR(255),
    COMMENTS_COUNT VARCHAR(255),
    POST_SECTION_NAME VARCHAR(255),
    DESCRIPTION_HTML VARCHAR(255),
    FILE_LOCATION VARCHAR(255),
    CLASS VARCHAR(255),
    SCORE VARCHAR(255),
    PRE_SOFTMAX_SCORE VARCHAR(255),
    CORRECT_CLASS VARCHAR(255),
    PRIMARY KEY (MEME_ID)
);

CREATE INDEX IDX_MEME_ID on MEME (MEME_ID(36));
CREATE INDEX IDX_UP_VOTE_COUNT on MEME (UP_VOTE_COUNT);
CREATE INDEX IDX_DOWN_VOTE_COUNT on MEME (DOWN_VOTE_COUNT);
CREATE INDEX IDX_CLASS on MEME (CLASS(10));

DROP TABLE TAG;

CREATE TABLE TAG(
    TAG_ID VARCHAR(255),
    MEME_ID VARCHAR(255),
    TAG_KEY VARCHAR(255),
    URL VARCHAR(255),
    PRIMARY KEY (TAG_ID)
);

CREATE INDEX IDX_TAG_ID on TAG (TAG_ID(36));
CREATE INDEX IDX_TAG_KEY on TAG (TAG_KEY(10));
CREATE INDEX IDX_MEME_ID on TAG (MEME_ID(36));

DROP TABLE JOB;

CREATE TABLE JOB(
    JOB_ID VARCHAR(255),
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    PRIMARY KEY (JOB_ID)
);

CREATE INDEX IDX_JOB_ID on JOB (JOB_ID(36));
CREATE INDEX IDX_START_TIME on JOB (START_TIME);
CREATE INDEX IDX_END_TIME on JOB (END_TIME);

DROP TABLE TEMPLATE;

CREATE TABLE TEMPLATE(
    FILE_PATH VARCHAR(255),
    TITLE VARCHAR(255),
    DOWNLOAD_URL VARCHAR(255),
    ID INT AUTO_INCREMENT,
    PRIMARY KEY (ID)
);

CREATE INDEX IDX_TEMPLATE_ID on TEMPLATE (TEMPLATE_ID(36));

DROP TABLE TRACKER;

CREATE TABLE TRACKER(
    INSERT_TIMESTAMP TIMESTAMP,
    ITERATION INT,
    ID INT,
    NEXT_CURSOR VARCHAR(255),
    PRIMARY KEY (NEXT_CURSOR)
);

CREATE INDEX IDX_TRACKER_TIMESTAMP on TRACKER (INSERT_TIMESTAMP);

CREATE INDEX IDX_TRACKER_ITERATION on TRACKER (ITERATION);

CREATE INDEX IDX_TRACKER_ID on TRACKER (ID);


